#!/bin/sh
echo tools/mkimage /usr/bin/
echo tools/mksunxiboot /usr/bin/
echo tools/kwboot /usr/bin/
echo tools/env/fw_printenv /usr/bin/
echo doc/mkimage.1 /usr/share/man/man1/

# manpages
echo debian/manpages/fw_printenv.8 /usr/share/man/man8/
echo debian/manpages/fw_setenv.8 /usr/share/man/man8/

# example env configs
for env_config in debian/env-configs/*.config ; do
	echo ${env_config} /usr/share/doc/u-boot-tools/examples/
done
